### GET all posts
GET http://localhost:3000/

###

### Create a new post
POST http://localhost:3000/create
Content-Type: application/json

{
  "content": "This is a test post from httpyac",
  "author": "httpyac"
}
